site_name: Astral Protocol API Documentation
site_url: https://api.astral.global/docs/  # Your actual documentation URL
repo_url: https://github.com/DecentralizedGeo/astral-api # Link to your repository
edit_uri: edit/main/docs/  # If you want "Edit this page" links on GitHub

theme:
  name: material # Use the mkdocs-material theme
  features:
    - navigation.sections  # Enable section-based navigation
    - navigation.top
    - toc.integrate
    - search
    - content.code.copy

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
  - Data Model: data-model.md
  - Spatial Queries: spatial-queries.md
  - Authentication: authentication.md
  - Troubleshooting: troubleshooting.md
  - OGC API: ogc-api.md
  - GraphQL API: graphql-api.md
  - Documentation Review: documentation-review.md # If you want to include internal docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search 